#import "control-blocks.typ": *

#let sys_block = diagram(
  spacing: (1.5em, 1.5em),
  node-stroke: 1pt,
  mark-scale: 80%,
  let line = -2,
  let (O1, O2, O3) = ((1, line), (4, line), (7, line)),
  rnode(O2, ctext("系统")),
  arrow(O1, O2, ctext("输入")),
  arrow(O2, O3, ctext("输出")),
)

#let sys_simple = diagram(
  spacing: (1.5em, 1.5em),
  node-stroke: 1pt,
  mark-scale: 80%,
  let line = -2,
  let (O1, O2) = ((-2, line), (11, line)),
  let (C, A, P) = ((1, line), (5, line), (7, line)),
  rnode(C, ctext("控制器")),
  rnode(A, ctext("执行器")),
  rnode(P, ctext("过程")),
  arrow(O1, C, ctext("指令变量")),
  arrow(C, A, ctext("执行信号")),
  arrow(A, P, ctext("受操纵变量")),
  arrow(P, O2, ctext("受控信号")),
  let (B1, B2) = ((2.5, line), (9.5, line)),
  let B3 = (6, line + 1),
  dash(B1, B3, "", corner: left),
  dash(B3, B2, "", corner: left),
  label(B3, "工厂"),
)

#let sys_closed = diagram(
  spacing: (1.5em, 1.5em),
  node-stroke: 1pt,
  mark-scale: 80%,
  let line1 = 0.5,
  let line2 = 2,
  let (R, O, T, A) = ((1, line1), (3, line1), (5.5, line1), (9, line1)),
  let S = (5.5, line2),
  rnode(R, $V(s)$),
  onode(O, ""),
  label((3, line1 - 0.75), ctext("误差表")),
  label((3 - 0.4, line1 - 0.25), text("+", size: 0.8em)),
  label((3 - 0.2, line1 + 0.35), text("-", size: 1.2em)),
  rnode(T, ctext("控制器")),
  rnode(S, ctext("传感器")),
  rnode(A, ctext("执行器")),
  arrow(R, O, ""),
  arrow(O, T, ctext("指令信号")),
  arrow(T, A, ctext("执行信号")),
  arrow(A, S, "", corner: right),
  arrow(S, O, ctext("传感变量"), label-pos: 0.75, corner: right),
)
